action_id: trunk-cache-prune
date: 2025-10-21 00:57:04
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1761008224
full_timestamp:
  nanos: 182327000
  seconds: 1761008224
trunk_version: 1.25.0
