@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\stian\AppData\Local\trunk\tools\trufflehog\3.90.11-daa6080d5bbd8a0c162ab9598838c29d;C:\Users\stian\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\stian\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
