action_id: trunk-share-with-everyone
date: 2025-10-21 11:22:17
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1761045737
full_timestamp:
  nanos: 419494000
  seconds: 1761045737
trunk_version: 1.25.0
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
